// Generated by Cypress Author on 21 May 2026
describe("KWIC Tool", () => {
  beforeEach(() => {
    cy.visit("/tools/kwic");
  });

  it("KWIC tool specific settings - window", () => {
    cy.getByData("kwic-word-window").within(() => {
      cy.contains(
        "Välj hur många ord som ska visas till vänster och höger om sökorden",
      );
    });
    cy.getByData("kwic-window-left")
      .clear()
      .type("{uparrow}")
      .should("have.value", "1");
    cy.getByData("kwic-window-left")
      .type("{downarrow}{downarrow}")
      .should("have.value", "1");
    cy.getByData("kwic-window-left")
      .clear()
      .type("20")
      .should("have.value", "20");
    cy.getByData("kwic-window-left")
      .type("{uparrow}")
      .should("have.value", "20");
  });

  it("KWIC tool specific settins - lemmatization toogle", () => {
    cy.getByData("kwic-lemma-toggle").should("contain", "Lemma");
    cy.getByData("kwic-lemma-toggle")
      .children()
      .find('[role="switch"]')
      .click();
    cy.getByData("kwic-lemma-toggle").children().find('[aria-checked="true"]');
    cy.getByData("kwic-lemma-toggle")
      .children()
      .find('[role="switch"]')
      .click();
    cy.getByData("kwic-lemma-toggle").children().find('[aria-checked="false"]');
  });

  it("Metadatadisplay is visible after search", () => {
    cy.getByData("kwic-show-data").as("showData").should("not.be.visible");
    cy.getByData("search-bar").type("månsken");
    cy.getByData("search-button-kwic").click();
    cy.get("@showData", { timeout: 10000 }).should("be.visible");
    cy.get("@showData").within(() => {
      cy.contains("År");
      cy.contains("Talare");
      cy.contains("Kammare");
      cy.contains("Parti");
      cy.contains("Kön");
      cy.contains("Data-version");
      cy.contains("SWERIK-records")
        .should("have.attr", "href")
        .and("include", "https://github.com/swerik-project/riksdagen-records");
      cy.contains("SWERIK-persons")
        .should("have.attr", "href")
        .and("include", "https://github.com/swerik-project/riksdagen-persons");
    });
  });

  it("Kwic search → displays results", () => {
    cy.getByData("search-bar").type("hundskatt");

    cy.getByData("search-button-kwic").click();

    cy.getByData("kwic-results-table", { timeout: 20000 })
      .scrollIntoView()
      .should("exist");
  });

  it("Click first row → expands and shows speech details and buttons", () => {
    cy.getByData("search-bar").type("hundskatt");
    cy.getByData("search-button-kwic").click();
    cy.getByData("kwic-results-table", { timeout: 10000 }).should("exist");

    cy.getByData("table-row").first().click();
    cy.getByData("expanded-row-content").first().as("firstExpandedRow");

    // Stub window.open before interactions to prevent opening new windows
    cy.window().then((win) => {
      cy.stub(win, "open").as("windowOpen");
    });

    cy.get("@firstExpandedRow").within(() => {
      // :visible required due to different buttons with different view size
      cy.getByData("wikidata-button").should("exist");
      cy.getByData("open-source-button").should("exist");
      cy.getByData("download-button").should("exist");

      cy.getByData("wikidata-button")
        .should("have.attr", "href")
        .and("include", "wikidata.org");

      cy.getByData("wikidata-button").should("have.attr", "target", "_blank");

      cy.getByData("open-source-button").click();
    });

    // Verify window.open was called with correct path and target
    cy.get("@windowOpen").should("have.been.calledOnce");
    cy.get("@windowOpen").should((stub) => {
      const [path, target] = stub.firstCall.args;
      expect(path).to.match(/\/(pdf-pagewise|pdf)$/);
      expect(target).to.equal("_blank");
    });

    // Verify sessionStorage was set with PDF data
    cy.window().then((win) => {
      const pdfData = win.sessionStorage.getItem("pdfData");
      expect(pdfData).to.exist;
      const data = JSON.parse(pdfData);
      expect(data).to.have.property("speakerNote");
      expect(data).to.have.property("speechText");
      expect(data).to.have.property("speakerData");
      expect(data).to.have.property("page");
    });

    cy.get("@firstExpandedRow").within(() => {
      // Test download button functionality
      // Stub URL.createObjectURL to prevent actual file download
      cy.window().then((win) => {
        cy.stub(win.URL, "createObjectURL").returns("blob:mock-url");
        cy.stub(win.URL, "revokeObjectURL");
      });

      cy.getByData("download-button").click();

      // Verify the download was triggered (createObjectURL was called)
      cy.window().then((win) => {
        expect(win.URL.createObjectURL).to.be.called;
      });
    });
  });
});
