// Generated by Cypress Author on 21 May 2026
describe("KWIC Tool", () => {
  beforeEach(() => {
    cy.visit("/tools/kwic");
  });

  it("Kwic search → displays results", () => {
    cy.getByData("search-bar").type("hundskatt");

    cy.getByData("search-button-kwic").click();

    cy.getByData("kwic-results-table", { timeout: 20000 })
      .scrollIntoView()
      .should("exist");
  });

  it.only("Click first row → expands and shows speech details", () => {
    cy.getByData("search-bar").type("hundskatt");
    cy.getByData("search-button-kwic").click();
    cy.getByData("kwic-results-table", { timeout: 10000 }).should("exist");

    cy.getByData("table-row").first().click();
    cy.getByData("expanded-row-content").first().as("firstExpandedRow");

    // Stub window.open before interactions to prevent opening new windows
    cy.window().then((win) => {
      cy.stub(win, "open").as("windowOpen");
    });

    cy.get("@firstExpandedRow").within(() => {
      // :visible required due to different buttons with different view size
      cy.getByData("wikidata-button").filter(":visible").should("exist");
      cy.getByData("open-source-button").filter(":visible").should("exist");
      cy.getByData("download-button").filter(":visible").should("exist");

      // Verify the wikidata link href
      cy.getByData("wikidata-button")
        .filter(":visible")
        .should("have.attr", "href")
        .and("include", "wikidata.org");

      // Verify target="_blank" attribute (opens in new tab)
      cy.getByData("wikidata-button")
        .filter(":visible")
        .should("have.attr", "target", "_blank");

      // Test open-source button (uses window.open, not href)
      cy.getByData("open-source-button").filter(":visible").click();
    });

    // Verify window.open was called with correct path and target
    cy.get("@windowOpen").should("have.been.calledOnce");
    cy.get("@windowOpen").should((stub) => {
      const [path, target] = stub.firstCall.args;
      expect(path).to.match(/\/(pdf-pagewise|pdf)$/);
      expect(target).to.equal("_blank");
    });

    // Verify sessionStorage was set with PDF data
    cy.window().then((win) => {
      const pdfData = win.sessionStorage.getItem("pdfData");
      expect(pdfData).to.exist;
      const data = JSON.parse(pdfData);
      expect(data).to.have.property("speakerNote");
      expect(data).to.have.property("speechText");
      expect(data).to.have.property("speakerData");
      expect(data).to.have.property("page");
    });

    cy.get("@firstExpandedRow").within(() => {
      // Test download button functionality
      // Stub URL.createObjectURL to prevent actual file download
      cy.window().then((win) => {
        cy.stub(win.URL, "createObjectURL").returns("blob:mock-url");
        cy.stub(win.URL, "revokeObjectURL");
      });

      cy.getByData("download-button").filter(":visible").click();

      // Verify the download was triggered (createObjectURL was called)
      cy.window().then((win) => {
        expect(win.URL.createObjectURL).to.be.called;
      });
    });
  });
});
